import type { Metadata } from "next";
import "./input.css"
import Link from "next/link";



export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
  <body>
    <nav className="absolute top-16 h-16 w-screen flex-col justify-between ">
      <div className="absolute left-16">
        <p className="font-Inter font-bold text-2xl">KIM PAX</p>
      </div>
      <div className="flex items-center justify-end absolute right-24 space-x-10">
        <Link href={'#'} className="font-Inter font-semi-bold text-lg ">Home</Link>
        <Link href={'/order'} className="font-Inter font-semi-bold text-lg">Order</Link>
        <Link href={'/about'} className="font-Inter font-semi-bold text-lg">About us</Link>
      </div>
    </nav>
    {children}
  </body>
</html>
  );
}
